- .gitignore
- scripts/generate_example_records.js
* Makes `scripts/generate_example_records.json` work out of the box
by adding the proper requires and making it executable.
* Also adds `node_modules` to `.gitignore` so that we can `npm install
json-schema-faker` locally.
Signed-off-by: Jacopo Notarstefano <jacopo.notarstefano@cern.ch>
> scripts: fix generate_example_records

- inspire_schemas/records/hep.json
* Insertion of the `$schema` and `control_number` fields in the hep schema
as it is required for using invenio-records-rest PUT request upon updating
a single record.
Signed-off-by: Zacharias Zacharodimos <zacharias.zacharodimos@cern.ch>
> hep: Insertion of fields `$schema` and `control_number` in hep.json.

- inspire_schemas/records/authors.json
* Since we still need to import/export from legacy, reintroduce
explicit old_emails and emails in positions to avoid losing information.
> authors: reintroduce old_emails

- inspire_schemas/records/hep.json
INCOMPATIBLE Adds the `$schema` and `control_number` fields to the hep
schema because they are required by `invenio-records-rest` to support PUT
requests.
> hep: add $schema and control_number

- inspire_schemas/records/authors.json
- inspire_schemas/records/conferences.json
- inspire_schemas/records/elements/external_field.json
- inspire_schemas/records/elements/inspire_field.json
- inspire_schemas/records/experiments.json
- inspire_schemas/records/hep.json
- inspire_schemas/records/institutions.json
- inspire_schemas/records/jobs.json
- scripts/generate_example_records.js
- tests/integration/fixtures/authors_example.json
- tests/integration/fixtures/conferences_example.json
- tests/integration/fixtures/experiments_example.json
- tests/integration/fixtures/hep_example.json
- tests/integration/fixtures/institutions_example.json
- tests/integration/fixtures/jobs_example.json
- tests/integration/fixtures/journals_example.json
This change is:
- removing the field: `field_categories`
- adding 2 field: `external_field_categories` and `inspire_field_categories`
In order to maintain different lists for the categories of INSPIRE and the categories that we receive from external sites, during the articles collection
> Refactor the field_categories

- inspire_schemas/records/authors.json
- inspire_schemas/records/conferences.json
- inspire_schemas/records/elements/inspire_field.json
- inspire_schemas/records/experiments.json
- inspire_schemas/records/hep.json
- inspire_schemas/records/institutions.json
- inspire_schemas/records/jobs.json
* Removes unnecessary oneOf from schemas.
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>
> Remove oneOf from schemas

- inspire_schemas/records/hep.json
* INCOMPATIBLE removes page_nr which was confusing everyone
* NEW adds number_of_pages for the number of pages in the document
* Closes #63
> hep: number_of_pages instead of page_nr

- inspire_schemas/records/hep.json
* FIX Fixes arXiv eprint regexp, so that it correctly catches
optional subcategories.
> hep: fix arXiv eprint regexp

- inspire_schemas/records/hep.json
* INCOMPATIBLE Restructures the way to store CRediT roles and INSPIRE
roles.
* NEW Introduces support for raw values.
> hep: finalize author structure

- inspire_schemas/records/hep.json
- tests/integration/fixtures/hep_example.json
* INCOMPATIBLE Merges classification_number into keywords field.
(closes #52)
* INCOMPATIBLE Renames keywords.keyword->keywords.value,
keywords.classification_scheme->keywords.schema
* NEW Introduces an enum for keywords.schema.
> hep: merge classification_number into keywords

- inspire_schemas/records/hep.json
* INCOMPATIBLE removes "thesis_supervisor", which is superseded by the
"supervisor" value in "inspire_roles"
> hep: thesis_supervisor superseded by inspire_roles

- inspire_schemas/records/authors.json
- inspire_schemas/records/conferences.json
- inspire_schemas/records/elements/acquisition_source.json
- inspire_schemas/records/elements/address.json
- inspire_schemas/records/elements/contact.json
- inspire_schemas/records/elements/id.json
- inspire_schemas/records/elements/inspire_field.json
- inspire_schemas/records/elements/json_reference.json
- inspire_schemas/records/elements/reference.json
- inspire_schemas/records/elements/title.json
- inspire_schemas/records/elements/url.json
- inspire_schemas/records/experiments.json
- inspire_schemas/records/hep.json
- inspire_schemas/records/institutions.json
- inspire_schemas/records/jobs.json
- inspire_schemas/records/journals.json
* BETTER Adds noAdditionalProperties everywhere.
(closes #26)
> schemas: add noAdditionalProperties everywhere

- inspire_schemas/records/authors.json
- inspire_schemas/records/hep.json
- tests/integration/fixtures/authors_example.json
- tests/integration/fixtures/hep_example.json
* INCOMPATIBLE kills collections for hep and authors.
- In hep, collections have been superseded by document_type,
publication_type, citeable, refereed, special_collections.
-For authors, it is completely useless as the existing values on
legacy are 'USEFUL' and 'HEPNAMES', both of which have special
meaning.
* INCOMPATIBLE also pluralizes special_collections, which is an array.
> schemas: kill collections

- inspire_schemas/records/hep.json
* NEW adds hidden key to report_numbers, to mark the report numbers that
need to be indexed and searchable, but not displayed to the user.
> hep: add hidden report numbers

- inspire_schemas/records/hep.json
* INCOMPATIBLE adds "categories" to the required keys of "arxiv_eprints"
and force it to have at least one element.
> hep: require at least one arXiv category

- inspire_schemas/records/elements/degree_type.json
* Adds missing `thesis` to `degree_type.json` element.
Signed-off-by: Spiros Delviniotis <spyridon.delviniotis@cern.ch>
> elements: add thesis to degree_type

- inspire_schemas/records/hep.json
We have it in [current usage](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/dojson/current_marcxml_usage/hep.txt#L6034).
> hep: add jacow keyword schema

- inspire_schemas/records/authors.json
- inspire_schemas/records/conferences.json
- inspire_schemas/records/hep.json
- tests/integration/fixtures/hep_example.json
* INCOMPATIBLE All 'value's are now required.
* The ISBN pattern has been relaxed, as there are invalid ISBNs in the
nature, which we still want to keep track of.
> schemas: strictness changes some fields

- inspire_schemas/api.py
- inspire_schemas/records/elements/acquisition_source.json
- tests/integration/fixtures/authors_example.json
- tests/integration/fixtures/hep_example.json
* INCOMPATIBLE Uses for `method` the enum that was previously used for
`source`. `source` is for where the information comes from, `method` for
how we obtained it.
* `source` uses the source element.
* Adds `internal_uid` key for the user identifiers on the server.
> schemas: changes in acquisition_source

- inspire_schemas/records/authors.json
- inspire_schemas/records/conferences.json
- inspire_schemas/records/experiments.json
- inspire_schemas/records/hep.json
- inspire_schemas/records/institutions.json
- inspire_schemas/records/jobs.json
- inspire_schemas/records/journals.json
- tests/integration/fixtures/authors_example.json
- tests/integration/fixtures/conferences_example.json
- tests/integration/fixtures/experiments_example.json
- tests/integration/fixtures/hep_example.json
- tests/integration/fixtures/institutions_example.json
- tests/integration/fixtures/jobs_example.json
- tests/integration/fixtures/journals_example.json
* NEW Introduces new legacy_creation_date field that allows to
preserve the creation date when migrating from INSPIRE legacy.
* Ideally this field could disappear, after having implemented
a migration script that would map legacy_creation_date back
to the proper database column.
> general: new legacy_creation_date

- inspire_schemas/records/elements/id.json
- tests/integration/fixtures/authors_example.json
- tests/integration/fixtures/conferences_example.json
- tests/integration/fixtures/experiments_example.json
- tests/integration/fixtures/hep_example.json
- tests/integration/fixtures/institutions_example.json
- tests/integration/fixtures/jobs_example.json
- tests/integration/fixtures/journals_example.json
* INCOMPATIBLE `type` is renamed to `schema` for consistency.
* Adds old `SPIRES` id.
(closes #93)
> elements: changes in id

- inspire_schemas/records/conferences.json
- inspire_schemas/records/experiments.json
- inspire_schemas/records/institutions.json
- inspire_schemas/records/jobs.json
- tests/integration/fixtures/authors_example.json
- tests/integration/fixtures/conferences_example.json
- tests/integration/fixtures/experiments_example.json
- tests/integration/fixtures/hep_example.json
- tests/integration/fixtures/institutions_example.json
- tests/integration/fixtures/jobs_example.json
- tests/integration/fixtures/journals_example.json
* Adds `external_system_identifiers` for all schemas but authors (which
uses `ids` instead, containing both internal and external identifiers).
* INCOMPATIBLE Renames in institutions `ids` to
`external_system_identifiers` for consistency.
> schemas: external_system_identifiers changes

- inspire_schemas/records/hep.json
- tests/integration/fixtures/hep_example.json
* Adds the `_files` key, which is produced by the literature suggestion
form. It was copy/pasted from the [Zenodo schema](https://github.com/zenodo/zenodo/blob/master/zenodo/modules/deposit/jsonschemas/deposits/records/record-v1.0.0.json#L447).
> hep: `_files` addition

- requirements-test.txt
- run-tests.sh
Also forcing a new release with the correct version. This commit might
be reverted after if so decided in the documentation meeting.
> tests: remove useless pydocstyle

- inspire_schemas/records/elements/id.json
```python
In [1]: schema = {'pattern': '^((\w|\-|\')+\.)+\d+$', 'type': 'string'}
In [2]: validate('L.Dell\'Asta.1', schema)
In [3]: validate('T.J.Berners-Lee.1', schema)
In [4]: with open('035__a_when_9_is_BAI.txt', 'r') as f:
...:     for line in f:
...:         try:
...:             validate(line.strip(), schema)
...:         except:
...:             print(line.strip())
```
prints
```
0000-0002-2836-6085
INSPIRE-00627028
INSPIRE-00584874
.J.M.Snellings.1
Qing.Ping.Ji.
Qi.Fang.Lü.1
10115251
.F.Schonfeld.1
```
where `035__a_when_9_is_BAI.txt` is a file containing all the BAIs I could find in HEPNames. These outliers could be interesting for @inspirehep/inspire-content. We don't want to allow characters like "ü" in BAIs, right?
> elements: expand regexp for BAIs

- inspire_schemas/records/hep.json
* INCOMPATIBLE Removes CDS from the allowed values of
`special_collections`, as `special_collections = ['CDS']` has been
superseded by `_export_to.CDS = true` in aee49d8.
> hep: remove CDS from special_collections

- inspire_schemas/records/hep.json
- tests/integration/fixtures/hep_example.json
* INCOMPATIBLE `editions` is now an array of strings, instead of an `edition` array of objects
with only one key, incidentally also called `edition`.
> hep: make editions less stupid

- inspire_schemas/builders.py
* Fixes the logic about citeable articles. Before it was considering
the publication_info field as an object rather than an array.
Signed-off-by: Riccardo Candido <riccardo.candido@gmail.com>
> builders: fix publication_info citeable logic

- inspire_schemas/builders.py
- tests/unit/test_hep_builder.py
* Moves `is_citeable` function outside form the class `LiteratureBuilder`
* Adds unit tests for the `is_citeable` function
Signed-off-by: Riccardo Candido <riccardo.candido@gmail.com>
> tests: add tests is_citeable function

- inspire_schemas/records/authors.json
- inspire_schemas/records/conferences.json
- inspire_schemas/records/experiments.json
- inspire_schemas/records/institutions.json
- inspire_schemas/records/jobs.json
- inspire_schemas/records/journals.json
- tests/integration/fixtures/authors_example.json
- tests/integration/fixtures/conferences_example.json
- tests/integration/fixtures/experiments_example.json
- tests/integration/fixtures/institutions_example.json
- tests/integration/fixtures/jobs_example.json
- tests/integration/fixtures/journals_example.json
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-nightly/group/619212/
INCOMPATIBLE adds the `deleted_records` key to all the schemas,
while previously it was only in HEP.
> global: add deleted_records everywhere

- inspire_schemas/builders.py
* We were missing the pubinfo_freetext from the publication_info.
> builders.LiteratureBuilder: add pubinfo_freetext

- inspire_schemas/records/elements/document_type.yml
- inspire_schemas/records/elements/reference.yml
- inspire_schemas/records/hep.yml
- tests/integration/fixtures/hep_example.json
* INCOMPATIBLE Significantly changes the reference element.
* Small changes in hep in the `references`.
* Also pulls `document_type` out of `hep` into an element for reuse in
reference.
> elements/reference: finalize subschema

- inspire_schemas/records/elements/acquisition_source.yml
- inspire_schemas/records/elements/inspire_field.yml
- inspire_schemas/records/elements/material.yml
- inspire_schemas/records/elements/reference.yml
- inspire_schemas/records/hep.yml
- tests/integration/fixtures/hep_example.json
* Fixes broken links in `description`s
* Reorders `description`s to put `:MARC:` first
* Corrects wrong `description` for `pubinfo_freetext`
* Adds `copyright` `year` to `hep`, which was missing
* Adds `translation` to the `material` enum
> small documentation changes and schema additions

- inspire_schemas/builders.py
- tests/integration/fixtures/expected_data_hep.yaml
- tests/integration/fixtures/input_data_hep.yaml
* Adds sample date to `material` field of `input_data_hep.yaml`.
* Adds `copyright.material` sample data to `expected_data_hep.yaml`.
* Fix wrong `url` sample to `copyright.url`.
* Fix: populate `copyright.material` field in `LiteratureBuilder`.
Closes #155 
Relates to https://github.com/inspirehep/hepcrawl/issues/128
> builder: `copyright.material` is not really populated

- inspire_schemas/builders.py
- tests/integration/fixtures/expected_data_hep.yaml
- tests/integration/test_builders.py
* Adds `copyright.year` field to tests.
* Adds missing `copyright.year` field to the `builders.add_copyright`.
Closes #157 
> builder: support `copyright.year` field

- inspire_schemas/builders.py
- tests/integration/fixtures/expected_data_hep.yaml
- tests/integration/fixtures/input_data_hep.yaml
- tests/integration/test_builders.py
* Adds `license.material` field to tests.
* Adds `license.imposing` field to tests.
* Adds: support for `license.material` field.
* Adds: support for `license.imposing` field.
Closes #161
Relates to https://github.com/inspirehep/hepcrawl/issues/128
> builder: support `license.material`, `license.imposing` fields

- inspire_schemas/builders.py
- tests/integration/fixtures/expected_data_hep.yaml
- tests/integration/test_builders.py
* Adds `dois.material` field to tests.
* Adds: support for `dois.material` field in `LiteratureBuilder`.
Closes #159
Relates to https://github.com/inspirehep/hepcrawl/issues/128
> builder: support `dois.material` field

- inspire_schemas/builders.py
- tests/integration/fixtures/expected_data_hep.yaml
- tests/integration/test_builders.py
* Adds `publication_info.material` field to tests.
* Adds: support for `publication.material` field.
Closes #164 
Relates to https://github.com/inspirehep/hepcrawl/issues/128
> builder: support `publication_info.material` field

- inspire_schemas/records/experiments.yml
- tests/integration/fixtures/experiments_example.json
INCOMPATIBLE An experiment can have multiple associated institutions,
but so far the schema has only allowed for one (closes #167).
> experiments: institution -> institutions

- inspire_schemas/builders.py
- inspire_schemas/records/authors.yml
- inspire_schemas/records/elements/acquisition_source.yml
- inspire_schemas/records/hep.yml
- tests/integration/fixtures/authors_example.json
- tests/integration/fixtures/expected_data_hep.yaml
- tests/integration/fixtures/hep_example.json
- tests/integration/fixtures/input_data_hep.yaml
- tests/integration/test_builders.py
* INCOMPATIBLE The field `acquisition_source` is replaced by the
`acquisition_sources` array, allowing to capture all sources of metadata
in the record instead of only one. This is useful as a record typically
aggregates information from several sources.
> schemas: promote acquisition_source to array

- inspire_schemas/records/authors.yml
- inspire_schemas/records/conferences.yml
- inspire_schemas/records/experiments.yml
- inspire_schemas/records/hep.yml
- inspire_schemas/records/institutions.yml
- inspire_schemas/records/jobs.yml
- inspire_schemas/records/journals.yml
* Fixes bug in `legacy_creation_date` by replacing `date-time` format
with `date`.
> schemas: legacy_creation_date is not a date-time

- inspire_schemas/records/hep.yml
- tests/integration/fixtures/hep_example.json
* Adds the `record_affiliations` field, which allows to migrate the 902
MARC field, used in older times when the affiliations could not
efficiently be associated to the individual authors.
> hep: add record_affiliations

- inspire_schemas/builders.py
- inspire_schemas/records/authors.yml
- inspire_schemas/records/elements/acquisition_source.yml
- inspire_schemas/records/hep.yml
- tests/integration/fixtures/authors_example.json
- tests/integration/fixtures/expected_data_hep.yaml
- tests/integration/fixtures/hep_example.json
- tests/integration/fixtures/input_data_hep.yaml
- tests/integration/test_builders.py
This reverts commit 670bc3e9f0d9a2ffff67d336737eacab87974006, as having
`acquisition_sources` as an array introduces too much complexity and
partially duplicates information stored elsewhere.
> Revert "schemas: promote acquisition_source to array"

- inspire_schemas/records/elements/id.yml
The pattern restricting Wikipedia page names was wrong. The actual rules for what is a valid wikipedia
page name are at
https://en.wikipedia.org/wiki/Wikipedia:Page_name#Technical_restrictions_and_limitations,
but this is too complex to implement as a pattern.
> elements/id: remove wikipedia pattern

- inspire_schemas/records/institutions.yml
* Many legacy records don't have a `110__a` or `110__b`, so they would
end up with an empty `institution_hierarchy`.
* Closes #183.
> institutions: don't require institution_hierarchy

- docs/conf.py
- docs/index.rst
- docs/resources/custom.css
- inspire_schemas/records/hep.yml
- requirements-docs.txt
- setup.py
This PR integrate the project jsonschema2rst inside inspire-schemas, allowing to auto generate schemas-documentation on the fly. The generated docs in linked by the main documentation page.
> Auto-generated Schemas documentation 

- inspire_schemas/records/experiments.yml
- tests/integration/fixtures/experiments_example.json
* INCOMPATIBLE Moves `legacy_name` to top-level in order to take into
account that not only experiments, but also accelerators can have a
`legacy_name`.
* Also documents how to spot an `accelerator`.
> experiments: make room for legacy accelerators

- inspire_schemas/records/institutions.yml
* Similarly to 88d7018, most institutions don't have a `110__t`.
* Closes #188.
> institutions: don't require ICN

- inspire_schemas/records/experiments.yml
* Since #187, `legacy_names` has moved out of `experiment`, so that
field can be empty now.
> experiments: relax constraints on required fields

- inspire_schemas/records/elements/id.yml
This reverts commit 8f6159d7cbf075654b0702a793509336f3928d4a.
No records are affected so it's not incompatible.
(OSTI is not for id.yml, which is for HepNames, for Literature)
> Revert "id: adding support for OSTI"

- inspire_schemas/records/elements/material.yml
* INCOMPATIBLE This reverts commit
264e4c7cfb9d36ef18a62a26efee4e7ee341ed60 following discussion at:
inspirehep/inspire-schemas#195
> Revert "material: add corrigendum"

- tests/unit/test_hep_builder.py
These tests ensure that the builder is able to populate all subfields that are present in the schema, since this was a bug that I fixed in https://github.com/inspirehep/inspire-schemas/pull/202 before merging it.
> tests: add tests for add_figure and add_documents

- inspire_schemas/utils.py
INCOMPATIBLE removes the deprecated `normalize_date_iso` method
as it's no longer used or needed.
> utils: remove normalize_date_iso

- inspire_schemas/builders/references.py
- inspire_schemas/records/elements/reference.yml
- tests/integration/fixtures/hep_example.json
- tests/unit/test_reference_builder.py
* INCOMPATIBLE `report_numbers` is now an array instead of the
`report_number` string. This is needed as sometimes more than one report
number appears in a single reference. Closes #209.
> element/references: allow several report_numbers

- inspire_schemas/records/elements/reference.yml
- inspire_schemas/records/elements/related_record.yml
- inspire_schemas/records/journals.yml
- tests/integration/fixtures/journals_example.json
This is a draft for the new journal schema. Any comments welcome.
The generated documentation now appears [here](http://inspire-schemas.readthedocs.io/en/docstests/schemas/records/journals.html).
@inspirehep/inspire-content (in particular @fschwenn and @cleggm1)
This is a continuation of PR #215.
> journals: attempt to finalize schema

- inspire_schemas/records/journals.yml
* INCOMPATIBLE `journal_title` and `short_title` are now required.
> journals: require journal and short titles

- inspire_schemas/builders/literature.py
- inspire_schemas/records/authors.yml
- inspire_schemas/records/conferences.yml
- inspire_schemas/records/experiments.yml
- inspire_schemas/records/hep.yml
- inspire_schemas/records/institutions.yml
- inspire_schemas/records/jobs.yml
- inspire_schemas/records/journals.yml
- tests/integration/fixtures/authors_example.json
- tests/integration/fixtures/conferences_example.json
- tests/integration/fixtures/expected_data_hep.yaml
- tests/integration/fixtures/experiments_example.json
- tests/integration/fixtures/hep_example.json
- tests/integration/fixtures/input_data_hep.yaml
- tests/integration/fixtures/institutions_example.json
- tests/integration/fixtures/jobs_example.json
- tests/integration/fixtures/journals_example.json
- tests/integration/test_builders.py
* INCOMPATIBLE Previously, the `_collections` was not used directly, as it was
managed by inveniosoftware/invenio-collections. This required to have an
extra field, `special_collections` that was modified instead.
> global: handle _collections directly

- inspire_schemas/records/elements/arxiv_categories.yml
* INCOMPATIBLE Removes some categories that have been subsumed into
another one, which are taken care of by inspirehep/inspire-dojson#22.
* Adds the new `econ.EM` category.
> elements/arxiv_categories: update categories

- inspire_schemas/records/hep.yml
This is just relaxing the pattern, therefore it's not an incompatible change.
> hep: make all patterns of ISBNs the same

- inspire_schemas/builders/literature.py
- tests/unit/test_literature_builder.py
* Previously, when `source` was `None`, the quoting was incorrect.
> builders: correct __repr__ of LiteratureBuilder

- inspire_schemas/utils.py
- package.json
- scripts/generate_example_records.js
- setup.py
- tests/integration/fixtures/authors_example.json
- tests/integration/fixtures/conferences_example.json
- tests/integration/fixtures/experiments_example.json
- tests/integration/fixtures/hep_example.json
- tests/integration/fixtures/institutions_example.json
- tests/integration/fixtures/jobs_example.json
- tests/integration/fixtures/journals_example.json
- tests/unit/test_api.py
* INCOMPATIBLE Extends the draft4 format checker to also validate
`format: date` (closes: #250).
* This also modifies the example generator script to produce real dates
by using `moment.js`.
> api: validate date format

- inspire_schemas/builders/references.py
- inspire_schemas/utils.py
- tests/unit/test_reference_builder.py
- tests/unit/test_utils.py
* This calls the new `convert_old_publication_info_to_new` util  in the
ReferenceBuilder.set_pubnote method to ensure that all references
contain the letter in the `journal_title` instead of the
`journal_volume`.
* Also refactors the split_pubnote util (that is not used outside the
ReferenceBuilder) to return a `dict` instead of a `tuple`, which
simplifies things.
> builders: split journal letter in ReferenceBuilder

- inspire_schemas/builders/literature.py
- tests/integration/test_builders.py
- tests/unit/test_literature_builder.py
Adds `add_reference` method to LiteratureBuilder.
Signed-off-by: Szymon Łopaciuk <szymon.lopaciuk@cern.ch>
> builders: add add_reference to literature builder

- docs/conf.py
Replaced open with codecs.open to write unicode to the `CHANGELOG.txt` file as UTF-8.
> fix UnicodeEncodeError when writing to the changelog

- inspire_schemas/builders/references.py
- tests/unit/test_reference_builder.py
To `ReferenceBuilder` add functionality to set:
- journal title, issue and volume
- start and end page and/or article id
Currently it's possible to do a workaround using `build_pubnote` and `set_pubnote`, however it's not possible to do that for `journal_issue` field. This adds above facilities to add the fields directly.
> builders: add journal related setters for references

- inspire_schemas/records/hep.yml
- tests/integration/fixtures/hep_example.json
* This allows to preserve the information of `9:CURATOR` and correctly
send it back to legacy.
> hep: add legacy_curated flag to references

- inspire_schemas/builders/references.py
- tests/unit/test_reference_builder.py
Detect and normalise arXiv IDs of the form `arXiv:hep-th/1601.07616`, which are technically invalid, but appear in APS records.
> builders: detect APS new-style arXiv ID with class

- inspire_schemas/builders/literature.py
- tests/unit/test_literature_builder.py
Add a "Submitted to..." public note for records which only have `journal_title` specified in `add_publication_info`.
> builders: add a public note for submitted records

- inspire_schemas/records/authors.yml
- inspire_schemas/records/conferences.yml
- inspire_schemas/records/elements/json_reference.yml
- inspire_schemas/records/elements/url.yml
- inspire_schemas/records/experiments.yml
- inspire_schemas/records/hep.yml
- inspire_schemas/records/institutions.yml
- inspire_schemas/records/jobs.yml
- inspire_schemas/records/journals.yml
- inspire_schemas/utils.py
- scripts/generate_example_records.js
- setup.py
- tests/integration/fixtures/authors_example.json
- tests/integration/fixtures/conferences_example.json
- tests/integration/fixtures/experiments_example.json
- tests/integration/fixtures/hep_example.json
- tests/integration/fixtures/institutions_example.json
- tests/integration/fixtures/jobs_example.json
- tests/integration/fixtures/journals_example.json
- tests/unit/test_api.py
- tests/unit/test_literature_builder.py
* INCOMPATIBLE This replaces the `url` `format` everywhere by `uri` (for
absolute URLs) or `uri-reference` (if the URL could be relative).  These
`format`s are part of the JSON schema spec (the second one starting from
Draft 6), whereas `url` is not. In order to validate these formats, this
package now depends on `rfc3987`, and adds a custom validator for
`uri-reference`, as we are currently on Draft 4 (closes #274).
Note that the `json-schema-faker` currently generates relative URIs for
`uri` (which is incompatible with Draft 6), so the fixtures had to be
amended by hand.
> global: use uri/uri-reference formats, not url

- inspire_schemas/records/elements/acquisition_source.yml
- inspire_schemas/records/elements/address.yml
- inspire_schemas/records/elements/arxiv_categories.yml
- inspire_schemas/records/elements/cnum.yml
- inspire_schemas/records/elements/contact.yml
- inspire_schemas/records/elements/country_code.yml
- inspire_schemas/records/elements/degree_type.yml
- inspire_schemas/records/elements/document_type.yml
- inspire_schemas/records/elements/id.yml
- inspire_schemas/records/elements/inspire_field.yml
- inspire_schemas/records/elements/json_reference.yml
- inspire_schemas/records/elements/language_code.yml
- inspire_schemas/records/elements/material.yml
- inspire_schemas/records/elements/rank.yml
- inspire_schemas/records/elements/records-files.yml
- inspire_schemas/records/elements/reference.yml
- inspire_schemas/records/elements/related_record.yml
- inspire_schemas/records/elements/source.yml
- inspire_schemas/records/elements/title.yml
- inspire_schemas/records/elements/url.yml
- inspire_schemas/utils.py
- tests/unit/test_utils.py
Closes https://github.com/inspirehep/inspire-schemas/issues/279.
According to the spec, ``$schema`` MUST NOT appear in subschemas.
See: http://json-schema.org/latest/json-schema-core.html#rfc.section.7
> elements: remove $schema from all elements

- inspire_schemas/records/hep.yml
- tests/integration/fixtures/hep_example.json
* This field is meant to hold the `035__9:DESY` MARC field, that was
previously put among the `external_system_identifiers`. That was
incorrect, as the identifier is not unique nor external.
> hep: add identifier to _desy_bookkeeping

- inspire_schemas/builders/signatures.py
* `filter` returns an iterator instead of a list in Python 3, so this
replaces it by a list comprehension. Also fixes some docstring errors.
> builders: make SignatureBuilder Python3 compatible

- inspire_schemas/utils.py
- tests/unit/test_utils.py
This fixes an issue with `filter_empty_parameters` where if all arguments provided to a decorated function as args (as opposed to kwargs) are empty, the filtered function would still be executed on all-empty arguments.
Can be reproduced by calling `LiteratureBuilder().add_abstract(None)`.
> utils: filter_empty_parameters if all are empty

- inspire_schemas/builders/literature.py
Commit 39c43b2 made ``language`` required in ``title_translations``,
but forgot to require it in the builder.
> builders: require language in add_title_translation

- inspire_schemas/records/elements/reference.yml
It can happen, that even if authors don't share a name, they may share initials in the references. With lack of other discerning information, we should allow them to be duplicated.
[Example](https://journals.aps.org/prx/abstract/10.1103/PhysRevX.7.041053), reference 43.
> elements.reference: allow repeated authors

- inspire_schemas/utils.py
- tests/unit/test_utils.py
Removes matching parentheses during collaborations normalization
> utils: handle parentheses in collaborations

- inspire_schemas/records/elements/reference.yml
The strings contained in `urls.value` are often not well-formed URIs.
In order not to make a large number of records fail migration, this
commit effectively removes the `format: uri` constraint on that field.
> elements/reference: urls don't have to be URIs

- inspire_schemas/builders/references.py
- tests/unit/test_reference_builder.py
Supersedes #300. This adds setters for imprint date and place. I called them `set_imprint_*` as I think `set_publication_date` could be ambiguous with `publication_info.year` field.
> builders: references: add imprint date and place

- inspire_schemas/utils.py
- setup.py
- tests/unit/test_utils.py
Adapt to ``isort@4.3.0``.
Make ``get_license_from_url`` handle CC public domain license URLs.
> utils: fix get_license_from_url

- inspire_schemas/records/data.yml
- tests/integration/fixtures/data_example.json
* NEW adds the `dois` field to the Data schema, which needs to be
populated in order to track citations to Data.
> data: add dois field

- inspire_schemas/utils.py
- tests/unit/test_utils.py
* Adds ``validation_errors`` utils function, which returns a generator
with all the schema errors. That is needed because normal JSONSchema
validation returns only the first error.
Signed-off-by: Harris Tzovanakis <me@drjova.com>
> utils: addition of ``draft`` validation

- inspire_schemas/utils.py
It turns out that it's not even doable without major rework on 3rd
parties.
See https://stackoverflow.com/questions/42158733/unicode-literals-and-doctest-in-python-2-7-and-python-3-5
> doctests: skip unicode result test

- inspire_schemas/utils.py
- setup.py
- tests/unit/test_utils.py
When converting journals from Legacy to Labs,
```
'journal_title': 'Phys.Rev.',
'journal_volume': 'D43',
```
turns into
```
'journal_title': 'Phys.Rev.D',
'journal_volume': '43',
```
.
Previously,
```
'journal_title': 'Eur.Phys.J.', 
'journal_volume': 'A28S1',
```
would turn into
```
'journal_title': 'Eur.Phys.J.A', 
'journal_volume': '28',
```
with the fix made in this PR, it would turn into
```
'journal_title': 'Eur.Phys.J.A', 
'journal_volume': '28S1',
```
as it's expected.
> utils: accept letters mid-volume in pub_info conversion

- inspire_schemas/records/institutions.yml
> institutions: add GRID to external system identifiers

- inspire_schemas/builders/authors.py
- tests/unit/test_author_builder.py
* Fixes the sorting when there are positions with and without start_date
* Fixes the sorting when there are positions with and without rank
> builders: fix author position sorting

- inspire_schemas/readers/conference.py
- tests/unit/test_conference_reader.py
Fixes a bug in the HAL push for some conference papers when the conference record contains a first address with no city, e.g. https://inspirehep.net/record/1651547.
cc @mathieugrives
> readers: more robust ConferenceReader.city

- docs/conf.py
- inspire_schemas/builders/authors.py
- tests/unit/test_author_builder.py
* Adds or updates (if hidden is not None) with `hidden` field to
indicate if email is public or not.
* NSPIR-2157
> builder: add email address with hidden field

- inspire_schemas/builders/literature.py
- tests/unit/test_literature_builder.py
Enables adding record objects for various fields:
* publication_info: conference_record, journal_record
* accelerator_experiment: record
* author: record
> literature: add record params

- inspire_schemas/builders/literature.py
- tests/unit/test_literature_builder.py
When harvesting OSTI via hepcrawl the `osti-id` of the record should be added to the literature record as `external_system_identifier`. This adds the necessary method to the LiteratureBuilder.
Signed-off-by: Thorsten Schwander <thorsten.schwander@gmail.com>
> literature builder: add external_system_identifier

- inspire_schemas/records/authors.yml
- inspire_schemas/records/conferences.yml
- inspire_schemas/records/data.yml
- inspire_schemas/records/elements/records-files.yml
- inspire_schemas/records/experiments.yml
- inspire_schemas/records/hep.yml
- inspire_schemas/records/institutions.yml
- inspire_schemas/records/jobs.yml
- inspire_schemas/records/journals.yml
`Invenio-records-files` introduced `_bucket` key added to every record
instance, also latest version adds `file_id` to `_files` file entry.
INSPIR-2589
> schemas: Update all schemas for invenio compatibility

- inspire_schemas/builders/__init__.py
- inspire_schemas/builders/authors.py
- inspire_schemas/builders/builder.py
- inspire_schemas/builders/conferences.py
- inspire_schemas/builders/jobs.py
- inspire_schemas/builders/literature.py
Code duplication of helper methods such as `_ensure_field` led to subtly diverging implementations across the builders. Let's put a stop to this by making all record builders inherit from a single `RecordBuilder` class containing the implementation of these helper methods.
> builders: refactor using inheritance

- inspire_schemas/records/elements/inspire_experiment_classification.yml
- inspire_schemas/records/experiments.yml
- tests/integration/fixtures/experiments_example.json
> experiments: add inspire_classification instead of class number

- .gitignore
- inspire_schemas/records/hep.yml
- tests/unit/test_literature_builder.py
`format: uri-reference` accepts pretty much anything.
but we want file urls (documents.url and figure.url)
to be either absolute url or relative `/api/files` url.
> literature: stricter file url validation

- inspire_schemas/utils.py
Use `re` module cache for compiled regexp.
> Remove unecessary global var

- inspire_schemas/records/hep.yml
Update the link to `CRediT` taxonomy, because according to the announcement at https://casrai.org/
CASRAI an organisation has ceased to exist, ... 
NISO is taking responsibility for the CRediT taxonomy. For more information, see http://credit.niso.org/
Signed-off-by: Thorsten Schwander <thorsten.schwander@gmail.com>
> hep schema: update link for CRediT taxonomy

- inspire_schemas/utils.py
- tests/unit/test_signature_builder.py
- tests/unit/test_utils.py
* Don't raise when the schema is unknown.
* Don't raise when schema don't match the value pattern.
* Ref: cern-sis/issues-inspire/issues/60
> signature builder: don't raise

- setup.py
new idutils version doesn't depend on isbnid package anymore but it is used in our code, so we have to require it ourself
> setup: add isbnid package dep

- inspire_schemas/parsers/arxiv.py
- inspire_schemas/parsers/elsevier.py
- inspire_schemas/parsers/jats.py
- inspire_schemas/parsers/utils.py
- setup.py
- tests/unit/test_parsers_arxiv.py
- tests/unit/test_parsers_author_xml.py
- tests/unit/test_parsers_crossref.py
- tests/unit/test_parsers_elsevier.py
- tests/unit/test_parsers_jats.py
* ref: https://github.com/cern-sis/issues-inspire/issues/546
The `utils.py` file and the `scrapy` and `pylatexenc` dependencies where missing when moving the parsers from `inspire-utils`. This went unnoticed as the tests were still passing since the new version of `inspire-utils` with the parsers removed had not been released yet when the tests ran. It is now released so we should now be able to trust the test results :)
> global: fix parser imports and add missing deps

- .github/workflows/build-and-release.yml
- scripts/normalize_yaml.py
- setup.py
- tests/integration/test_builders.py
- tests/unit/test_parsers_crossref.py
- tests/unit/test_parsers_elsevier.py
- tests/unit/test_parsers_jats.py
bump pyyaml to 6.x in order to be able to use inspire-schemas for: https://github.com/cern-sis/issues-inspire/issues/574
Remove urlib3 dependency
> global: update pyyaml version

- inspire_schemas/builders/data.py
- tests/integration/test_builders.py
- tests/unit/test_data_builder.py
ref: https://github.com/cern-sis/issues-inspire/issues/628
> data: add creation_date to the Data builder

- inspire_schemas/records/elements/acquisition_source.yml
* ref: cern-sis/issues-inspire/issues/630
> data: add hepdata as acquisitionsource

- inspire_schemas/builders/data.py
- tests/integration/test_builders.py
- tests/unit/test_data_builder.py
- Also Added record validation in unit tests in order to avoid testing wrong behavior, as was previously happening with test_add_literature.
ref: https://github.com/cern-sis/issues-inspire/issues/631
> feat[DataBuilder]: Pass doi value directly when adding literature
