inspirehep/inspire-schemas

requirements-docs.txt
=> docs: Fixed packaging issues

README.rst, docs/conf.py, docs/index.rst
* Fix link for the docs themselves.
* Fix changelog extension so it can be viewed on the browser.
=> docs: Minor fixes

.travis.yml, MANIFEST.in, docs/api.rst, docs/utils.rst, inspire_schemas/api.py, inspire_schemas/errors.py, inspire_schemas/records/conferences.json, inspire_schemas/records/institutions.json, inspire_schemas/utils.py, requirements-docs.txt, requirements-test.txt, requirements.txt, run-tests.sh, scripts/generate_example_records.js, setup.py, tests/integration/fixtures/authors_example.json, tests/integration/fixtures/conferences_example.json, tests/integration/fixtures/experiments_example.json, tests/integration/fixtures/hep_example.json, tests/integration/fixtures/institutions_example.json, tests/integration/fixtures/jobs_example.json, tests/integration/fixtures/journals_example.json, tests/integration/test_validate.py, tests/unit/test_api.py, tests/unit/test_utils.py
* NEW First public utility for the module, it just validates the
given data against the given schema (by name).
=> api: add the validate function

inspire_schemas/records/authors.json, inspire_schemas/records/elements/acquisition_source.json, inspire_schemas/records/hep.json, tests/integration/fixtures/authors_example.json
Let's see if I understood your `version_manager` script.
=> schemas: add acquisition_source to authors

docs/conf.py, requirements-build.txt, setup.py
=> packaging: moved to autosemver

setup.py
This solves a cyclic dependency issue that was found before, it's also
nicer :)
=> packaging: use autosemver through distutils

inspire_schemas/records/hep.json
Reverts 55b64dcee73ae518bc877f13ac0ee693396105af because it broke the build: https://travis-ci.org/inspirehep/inspire-next/builds/173215901
=> hep: revert $schema and control_number

README.rst
* Also force to bump version for pypi issue.
=> docs: minor lowercase change

inspire_schemas/records/authors.json, inspire_schemas/records/conferences.json, inspire_schemas/records/elements/id.json, inspire_schemas/records/experiments.json, inspire_schemas/records/institutions.json, inspire_schemas/records/journals.json
Signed-off-by: Jacopo Notarstefano <jacopo.notarstefano@cern.ch>
(closes #16)
=> schemas: add missing types

authors_example.json, conferences_example.json, experiments_example.json, hep_example.json, inspire_schemas/records/institutions.json, institutions_example.json, jobs_example.json, journals_example.json
As mentioned in https://github.com/inspirehep/inspire-next/pull/1807.
=> schemas: add ids to institutions

docs/index.rst
=> docs: add small note about version pinning

inspire_schemas/records/authors.json
* (closes #54).
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>
=> authors: add missing schema fields

inspire_schemas/records/hep.json
* becomes consistent with authors and other lists
* closes #59
=> hep: pluralize collaboration

inspire_schemas/utils.py, tests/unit/test_utils.py
=> utils.get_schema_path: add tests and refactor

inspire_schemas/records/elements/degree_type.json, inspire_schemas/records/hep.json, tests/integration/fixtures/authors_example.json, tests/integration/fixtures/hep_example.json
=> hep: minor enum fixes

inspire_schemas/records/elements/degree_type.json
This reverts commit 2b9decf26a0b5b060187aba334d1c1ab48f3da20.
=> Revert "elements: add thesis to degree_type"

inspire_schemas/records/authors.json, tests/integration/fixtures/authors_example.json
* INCOMPATIBLE Removes useless `_degree_type` key from `advisors`.
* Adds `ids` to `advisors`.
=> authors: advisors changes

inspire_schemas/records/hep.json, tests/integration/fixtures/hep_example.json
=> hep: add material in persistent_identifiers

inspire_schemas/records/hep.json, tests/integration/fixtures/hep_example.json
* Adds an _fft field, with contents based on
https://github.com/inspirehep/inspire/blob/master/bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py#L152-L164.
=> hep: new _fft field

inspire_schemas/records/hep.json, tests/integration/fixtures/hep_example.json
Fixes the bug pointed out in https://github.com/inspirehep/inspire-schemas/pull/88#issuecomment-280141222.
=> hep: make _fft an array

inspire_schemas/records/hep.json, tests/integration/fixtures/hep_example.json
=> hep: add missing `path` to `_fft`

inspire_schemas/records/hep.json, tests/integration/fixtures/hep_example.json
* INCOMPATIBLE makes `publication_type` and array.
=> hep: publication_type is an array

inspire_schemas/records/authors.json, inspire_schemas/records/institutions.json, tests/integration/fixtures/authors_example.json, tests/integration/fixtures/institutions_example.json
These are needed for the submissions (worked on by @jmartinm) and/or record migration (by @jacquerie).
=> Additions to the schema

inspire_schemas/records/hep.json, tests/integration/fixtures/hep_example.json
* INCOMPATIBLE Turns `_desy_bookkeeping` into an array of objects, as
there can be multiple entries.
=> hep: _desy_bookkeeping is an array

inspire_schemas/builders.py
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>
=> lit_builder: add date to acquisition_source

inspire_schemas/records/data.json
=> schemas: stub schema for data

inspire_schemas/records/hep.json, tests/integration/fixtures/hep_example.json
* INCOMPATIBLE This field does not contain any useful information, so it
was decided to remove it.
=> hep: remove publication_info.confpaper_info

inspire_schemas/records/elements/acquisition_source.json, tests/integration/fixtures/authors_example.json, tests/integration/fixtures/hep_example.json
Cherry pick of 3fbac012d4b9416c1d68331cdb6b298de758a19b from #105.
=> elements/acquisition_source: use datetime

inspire_schemas/records/hep.json
=> hep: add missing signature_block

inspire_schemas/builders.py
Should have been part of #122.
=> builders: fix add_acquisition_source

inspire_schemas/utils.py, tests/integration/fixtures/expected_data_hep.yaml
=> normalize_author: strip any spaces from the names

inspire_schemas/builders.py, tests/integration/fixtures/expected_data_hep.yaml
=> builder: don't create datetime for preprint_date

inspire_schemas/records/elements/acquisition_source.yml, inspire_schemas/records/elements/reference.yml, tests/integration/fixtures/hep_example.json
Closes https://github.com/inspirehep/inspire-schemas/issues/131
=> elements: add missing types

inspire_schemas/records/elements/url.yml, inspire_schemas/records/experiments.yml, tests/integration/fixtures/experiments_example.json
Generated docs are here: https://michamos.github.io/inspire-schemas/branch/experiment_schema/records/experiments.html
@annetteholtkamp @ksachs
=> experiments: finalize schema

inspire_schemas/records/hep.yml, tests/integration/fixtures/hep_example.json
Implements the schema part of inspirehep/inspire-next#1359.
=> hep: add hidden publication_info

inspire_schemas/records/elements/related_record.yml, inspire_schemas/records/experiments.yml, inspire_schemas/records/hep.yml, inspire_schemas/records/institutions.yml, inspire_schemas/records/journals.yml, scripts/generate_example_records.js, tests/integration/fixtures/experiments_example.json, tests/integration/fixtures/hep_example.json, tests/integration/fixtures/institutions_example.json, tests/integration/fixtures/journals_example.json
* INCOMPATIBLE Adds `related_records` for hep, experiments, journals and
institutions instead of the previous special cases (`succeeding_entry`,
`related_experiments`, `relation`, `related_institutes` respectively)
and the corresponding `related_record` element.
This is what we discussed with @annetteholtkamp and @jacquerie.
=> Related records

inspire_schemas/builders.py, inspire_schemas/utils.py
Addresses https://github.com/inspirehep/inspire-next/issues/2161
=> builders: don't use normalize_date_iso

inspire_schemas/records/conferences.yml, inspire_schemas/records/elements/address.yml, inspire_schemas/records/elements/country_code.yml, tests/integration/fixtures/conferences_example.json, tests/integration/fixtures/institutions_example.json, tests/integration/fixtures/jobs_example.json
Generated docs from the schema are here https://michamos.github.io/inspire-schemas/branch/conference_schema/records/conferences.html.
=> conferences: finalize schema

inspire_schemas/records/hep.yml
=> hep: don't use arXiv subcategories in eprint value

docs/conf.py, inspire_schemas/api.py, inspire_schemas/builders.py, inspire_schemas/utils.py, setup.py, tests/integration/fixtures/expected_data_hep.yaml, tests/integration/fixtures/input_data_hep.yaml, tests/integration/test_builders.py, tests/unit/test_hep_builder.py, tests/unit/test_utils.py
* Add parent record field to builder (publication_info) support #2159
=> Add parent_record field to builder

inspire_schemas/records/experiments.yml
=> experiments: make experiment.value not required

inspire_schemas/records/hep.yml, tests/integration/fixtures/hep_example.json
=> hep: use enum for energy ranges

inspire_schemas/records/hep.yml
* Adds the CDS hidden collection and BABAR internal collections to
`special_collections` and clarifies its description.
* Adds the INIS keyword schema.
=> hep: enlarge some enums

requirements-build.txt, setup.py
* Also adds the missing entry in install_requires.
Fixes #177
=> setup: remove unneeded setup dep to six

inspire_schemas/records/elements/related_record.yml, inspire_schemas/records/institutions.yml, tests/integration/fixtures/institutions_example.json
Schema is done and documented, but documentation generation failed because of some `jsonschema2rst` bug, so you will have to read the YAML.
=> Institution schema

inspire_schemas/records/hep.yml
=> hep: add value to special_collections

.travis.yml
Addresses https://github.com/inspirehep/inspire-schemas/issues/190
=> travis: allow failures on Python 3

inspire_schemas/records/elements/material.yml
=> material: add corrigendum

inspire_schemas/records/elements/id.yml
=> id: adding support for OSTI

inspire_schemas/records/hep.yml
=> hep: clarify _private_notes description

inspire_schemas/records/elements/records-files.yml, inspire_schemas/records/hep.yml, tests/integration/fixtures/hep_example.json
I didn't add the keys I asked about in #200 (`figures/name` and `figures/type`), if they are needed I will do an update.
=> hep: handle files properly

inspire_schemas/builders.py
Signed-off-by: Zacharias Zacharodimos <zacharias.zacharodimos@cern.ch>
=> builder: add methods for figures and documents

inspire_schemas/api.py
=> api: expose ReferenceBuilder

inspire_schemas/utils.py, setup.py, tests/unit/test_utils.py
=> utils: support unicode dashes in split_page_artid

inspire_schemas/builders/literature.py, inspire_schemas/utils.py, setup.py, tests/unit/test_utils.py
Renamed the function to something more representative, improved the implementation and logic behind the code and reduced vertical space of tests.
=> utils: improve author name normalizer

inspire_schemas/records/hep.yml, tests/integration/fixtures/hep_example.json
=> hep: add curated flag

inspire_schemas/builders/literature.py, tests/integration/fixtures/expected_data_hep.yaml, tests/integration/fixtures/input_data_hep.yaml, tests/integration/test_builders.py
=> literature: add subtitle parameter to add_title

inspire_schemas/builders/literature.py, tests/unit/test_literature_builder.py
* Some of the fields that an author could have were missing from the
builder, now they are present.
* Also adds missing schema validation to some LiteratureBuilder unit
tests.
=> builders: add missing fields to make_author

inspire_schemas/builders/literature.py, tests/integration/fixtures/expected_data_hep.yaml, tests/integration/fixtures/input_data_hep.yaml, tests/integration/test_builders.py
* Also slightly tweaks the setters for the other flags.
=> builders: add set_curated to LiteratureBuilder

inspire_schemas/utils.py, tests/unit/test_utils.py
Signed-off-by: Iuliana Voinea <iuliana.voinea@student.manchester.ac.uk>
=> utils: add arXiv utils

inspire_schemas/records/elements/arxiv_categories.yml
=> elements/arxiv_categories: also add eess.*

inspire_schemas/records/hep.yml, tests/integration/fixtures/hep_example.json
* INCOMPATIBLE This has been superseded by `documents` and `figures`.
=> hep: remove _fft field

inspire_schemas/builders/literature.py, inspire_schemas/utils.py, tests/unit/test_literature_builder.py, tests/unit/test_utils.py
Closes inspirehep/hepcrawl#176.
=> Builder improvements

inspire_schemas/builders/references.py, tests/unit/test_reference_builder.py
Closes inspirehep/inspire-dojson#69
=> reference_builder: use `normalize_author_name`.

inspire_schemas/builders/literature.py, inspire_schemas/utils.py, tests/unit/test_utils.py
=> builders: get license abbreviation from URL

inspire_schemas/builders/literature.py, tests/unit/test_literature_builder.py
=> builders: preserve license when no URL

inspire_schemas/records/elements/material.yml
* Also reorders and documents the various elements of the enum.
=> elements/material: add editorial note

inspire_schemas/builders/references.py, tests/unit/test_reference_builder.py
=> builders: better handling of reference pubnotes

inspire_schemas/utils.py, tests/unit/test_utils.py
=> utils: relax artid decision in split_page_artid

inspire_schemas/utils.py, tests/unit/test_utils.py
=> utils: improve classify_field

inspire_schemas/builders/literature.py, tests/unit/test_literature_builder.py
=> builders: handle None in LiteratureBuilder.add_doi

inspire_schemas/utils.py, setup.cfg, tests/unit/test_utils.py
https://www.youtube.com/watch?v=VKcAYMb5uk4
=> utils: handle journal letter split

inspire_schemas/utils.py, tests/unit/test_utils.py
=> utils: handle journal and volume renames in convert_* funcs

.gitignore, docs/conf.py, inspire_schemas/utils.py, setup.py, tests/integration/test_setup.py, tests/unit/test_utils.py
Signed-off-by: Glignos <glignos93@gmail.com>
=> setup:resolve schemas on build time

setup.py
That way it will install the dependencies (yaml) before running the
scripts.
=> setup: hook the json creation inside setuptools

inspire_schemas/resolved_records/__init__.py, inspire_schemas/resolved_records/elements/__init__.py, setup.py
Signed-off-by: Glignos <glignos93@gmail.com>
=> fixes resolved_records dir not being packaged

setup.py, tests/integration/test_setup.py
Signed-off-by: Glignos <glignos93@gmail.com>
=> setup: fixes recursive resolving

inspire_schemas/records/hep.yml
=> hep: add documentation for abstracts

inspire_schemas/builders/__init__.py, inspire_schemas/builders/literature.py, inspire_schemas/builders/signatures.py, inspire_schemas/errors.py, inspire_schemas/utils.py, tests/unit/test_signature_builder.py, tests/unit/test_utils.py
Create a builder for hep.authors records. This is a continuation of [@kaplun's work](https://github.com/kaplun/inspire-schemas/blob/signatures/inspire_schemas/builders/signatures.py)
This is a step towards inspirehep/inspire-next#2971
=> builders: create a signature builder

inspire_schemas/builders/literature.py, tests/unit/test_literature_builder.py
=> LiteratureBuilder: fail on duplicated docs and figures

inspire_schemas/records/elements/inspire_field.yml
=> elements/inspire_field: add CDS source

inspire_schemas/utils.py, tests/unit/test_utils.py
Closes https://github.com/inspirehep/inspire-schemas/issues/302.
=> utils: deduce year from volume for JHEP and JCAP

inspire_schemas/utils.py, tests/unit/test_utils.py
Sentry: https://sentry.inspirehep.net/inspire-sentry/prod/issues/848/
=> utils: don't raise if journal_volume is malformed

inspire_schemas/records/elements/related_record.yml
Signed-off-by: Glignos <glignos93@gmail.com>
=> add successor option for related records

inspire_schemas/records/hep.yml
Related issue: https://its.cern.ch/jira/browse/INSPIR-36
=> hep: don't require arXiv categories

inspire_schemas/builders/literature.py, tests/unit/test_literature_builder.py
=> builders: normalize dates in LiteratureBuilder

inspire_schemas/builders/references.py, inspire_schemas/utils.py, tests/unit/test_reference_builder.py, tests/unit/test_utils.py
=> builders: fix urls in ReferenceBuilder

inspire_schemas/builders/references.py, inspire_schemas/records/elements/reference.yml, tests/integration/fixtures/hep_example.json, tests/unit/test_reference_builder.py
=> elements: add external_system_identifiers to reference json schema

inspire_schemas/records/elements/reference.yml
=> elements: fix documentation reference json schema

inspire_schemas/builders/literature.py, inspire_schemas/utils.py, tests/integration/fixtures/expected_data_hep.yaml, tests/integration/fixtures/input_data_hep.yaml, tests/integration/test_builders.py, tests/unit/test_literature_builder.py
=> builders: add parent_isbn to LiteratureBuilder

inspire_schemas/builders/literature.py, tests/unit/test_literature_builder.py
=> builders: handle None orcids LiteratureBuilder

inspire_schemas/builders/authors.py, tests/unit/test_author_builder.py
Will be needed to create authors after disambiguation.
=> builders: create an author builder

inspire_schemas/builders/references.py, inspire_schemas/utils.py, tests/unit/test_reference_builder.py, tests/unit/test_utils.py
=> builders: fix _is_arxiv regex bug

inspire_schemas/builders/references.py, tests/unit/test_reference_builder.py
=> builders: don't accept invalid ADS/CDS urls in references

inspire_schemas/builders/references.py, tests/unit/test_reference_builder.py
=> builders: dedup report numbers in reference builder

inspire_schemas/records/authors.yml, inspire_schemas/records/elements/id.yml, inspire_schemas/records/elements/reference.yml, scripts/generate_example_records.js, tests/integration/fixtures/authors_example.json
I worked on this some time ago with @annetteholtkamp, but I never pushed because it is not strictly speaking final as we want to have user feedback about what there should be in author profile pages.
It still contains some useful refactorings, with useless fields removed and a clearer organization, so it might serve as a starting point.
This should probably not be merged before gathering the requirements as it will require changes in doJSON and in the formdata to model, which we might not want to do twice.
=> Author schema changes

inspire_schemas/builders/authors.py, tests/unit/test_author_builder.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
=> builders: addition of ``acquisition source`` in authors.

inspire_schemas/records/hep.yml
=> records: _collections field accepts SLAC

inspire_schemas/utils.py, tests/unit/test_utils.py
=> utils: ignore eConf when converting from old to new

.gitignore, inspire_schemas/builders/authors.py, tests/unit/test_author_builder.py
* Sorts institutions by respectively current, start_date and rank
* Sorts projects by respectively current and start_date
(INSPIR-1581)
=> authors: sort institutions and projects

inspire_schemas/utils.py, tests/unit/test_utils.py
=> utils: handle journal letters conversion with repeated letter

setup.py
=> utils: bump inspire-utils version

inspire_schemas/utils.py, setup.py, tests/unit/test_utils.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
=> utils: fix public domain licenses

setup.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
=> setup: bump pytest

inspire_schemas/records/hep.yml, tests/integration/fixtures/hep_example.json
=> records: add institutions ids to hep

inspire_schemas/builders/authors.py, tests/unit/test_author_builder.py
=> builders: add bai to authors

inspire_schemas/readers/__init__.py, inspire_schemas/readers/literature.py, tests/unit/test_literature_reader.py
=> readers: add literature reader INSPIR-1892

inspire_schemas/readers/__init__.py, inspire_schemas/readers/conference.py, inspire_schemas/readers/literature.py, tests/unit/test_conference_reader.py, tests/unit/test_literature_reader.py
=> readers: add conference reader

inspire_schemas/builders/authors.py, tests/unit/test_author_builder.py
=> author builder: add `add_previous_name` to builder

inspire_schemas/builders/authors.py, tests/unit/test_author_builder.py
=> builder: add `add_name_variant` to author builder

inspire_schemas/records/elements/contact.yml, inspire_schemas/records/elements/records-files.yml, inspire_schemas/records/elements/reference.yml, inspire_schemas/records/hep.yml, inspire_schemas/records/jobs.yml, tests/integration/fixtures/jobs_example.json
This adapts the job schema as discussed with Fermilab @hoc3426 @cleggm1.
=> Jobs schema

inspire_schemas/builders/__init__.py, inspire_schemas/builders/jobs.py, tests/integration/test_builders.py, tests/unit/test_job_builder.py
* Added builder for Jobs
INSPIR-2430
=> builder: Add builder for Jobs

inspire_schemas/records/elements/arxiv_categories.yml
=> elements: add eess.SY arXiv category

inspire_schemas/utils.py, tests/unit/test_utils.py
=> utils: strip trailing space in journal title

inspire_schemas/records/elements/acquisition_source.yml
=> schemas: add method beard for acquisition source

inspire_schemas/records/authors.yml, inspire_schemas/records/conferences.yml, inspire_schemas/records/data.yml, inspire_schemas/records/elements/records-files.yml, inspire_schemas/records/experiments.yml, inspire_schemas/records/hep.yml, inspire_schemas/records/institutions.yml, inspire_schemas/records/jobs.yml, inspire_schemas/records/journals.yml, tests/integration/fixtures/hep_example.json, tests/integration/fixtures/institutions_example.json
Also adds some missing constraints in for the new invenio-records-files fields.
cc @ArtemisLav
=> Add ROR identifiers

inspire_schemas/builders/__init__.py, inspire_schemas/builders/conferences.py, inspire_schemas/builders/jobs.py, tests/integration/fixtures/conferences_example.json, tests/integration/test_builders.py, tests/unit/test_conference_builder.py
* INSPIR-2852
Signed-off-by: Antonio Cesarano <cesarano2607@gmail.comk>
=> builder: add conference builder

inspire_schemas/builders/conferences.py, tests/unit/test_conference_builder.py
* INSPIR-2852
Signed-off-by: Antonio Cesarano <cesarano2607@gmail.comk>
=> conference: builder sanitizes `short_description`

inspire_schemas/records/authors.yml, inspire_schemas/records/hep.yml, tests/unit/test_author_builder.py
=> records: limit commas in name to two

inspire_schemas/builders/references.py, tests/unit/test_reference_builder.py
=> ReferenceBuilder: handle additional pubnotes

inspire_schemas/builders/references.py, tests/unit/test_reference_builder.py
Fixes https://sentry.inspirebeta.net/inspire-qa/next/issues/376241/?query=is%3Aunresolved
=> ReferenceBuilder: fix multiple additional pubnotes

inspire_schemas/records/authors.yml, inspire_schemas/records/hep.yml, inspire_schemas/records/seminars.yml, inspire_schemas/utils.py, scripts/generate_example_records.js, scripts/normalize_yaml.py, setup.py, tests/integration/fixtures/seminars_example.json, tests/unit/test_api.py
* INSPIR-3489
* Also updates `normalize_yaml.py` script to work on Python 3 instead of
Python 2.
=> seminars: add new schema type

inspire_schemas/builders/__init__.py, inspire_schemas/builders/builder.py, inspire_schemas/builders/seminars.py, tests/integration/fixtures/seminars_example.json, tests/integration/test_builders.py, tests/unit/test_seminar_builder.py
=> seminars: add builder

inspire_schemas/builders/seminars.py, inspire_schemas/records/seminars.yml, setup.py, tests/unit/test_seminar_builder.py
=> seminars: add related records field

inspire_schemas/builders/seminars.py, inspire_schemas/records/seminars.yml, tests/integration/fixtures/seminars_example.json, tests/integration/test_builders.py, tests/unit/test_seminar_builder.py
=> seminars: add accessibility info

inspire_schemas/utils.py, tests/unit/test_utils.py
=> utils: fix conversion of journal title and volume to new version

inspire_schemas/utils.py, tests/unit/test_utils.py
Ref: inspirehep/inspirehep#1208
=> ref. builder: improve arxiv recognition

inspire_schemas/builders/authors.py, inspire_schemas/records/authors.yml, tests/unit/test_author_builder.py
Ref: inspirehep/inspirehep#1347
=> authors: add hidden to advisors, positions, projects

inspire_schemas/builders/references.py, tests/unit/test_reference_builder.py
=> reference_builder: ignore authors without full_name

inspire_schemas/records/authors.yml, inspire_schemas/records/elements/inspire_experiment_classification.yml, inspire_schemas/records/elements/json_reference/author.yml, inspire_schemas/records/elements/json_reference/citeable.yml, inspire_schemas/records/elements/json_reference/conference.yml, inspire_schemas/records/elements/json_reference/data.yml, inspire_schemas/records/elements/json_reference/experiment.yml, inspire_schemas/records/elements/json_reference/institution.yml, inspire_schemas/records/elements/json_reference/job.yml, inspire_schemas/records/elements/json_reference/journal.yml, inspire_schemas/records/elements/json_reference/literature.yml, inspire_schemas/records/elements/json_reference/seminar.yml, inspire_schemas/records/experiments.yml, inspire_schemas/records/hep.yml, inspire_schemas/records/seminars.yml, tests/integration/fixtures/hep_example.json
* Ref inspirehep/inspirehep#1649.
* Also normalizes all YAML files.
Sem-ver: new feature
=> hep: add dedicated flag for RPP

inspire_schemas/utils.py, tests/unit/test_utils.py
=> utils: add collaboration_name_normalizer

inspire_schemas/builders/references.py, tests/unit/test_reference_builder.py
ref: inspirehep/inspirehep#1906
=> reference builder: don't double dois

inspire_schemas/builders/authors.py, tests/unit/test_author_builder.py
ref:inspirehep/inspirehep#2309
=> author builder: add current parameter to `add_email_address`

inspire_schemas/readers/literature.py, tests/unit/test_literature_reader.py
Ref: https://github.com/inspirehep/inspirehep/issues/2168
=> page range: fix bibtex artid return check

inspire_schemas/builders/literature.py, inspire_schemas/builders/signatures.py, tests/integration/fixtures/expected_data_hep.yaml, tests/integration/fixtures/input_data_hep.yaml, tests/integration/test_builders.py
Ref: https://github.com/cern-sis/issues-inspire/issues/19
=> add affiliations_identifiers to Literaturebuilder

.github/workflows/build-and-release.yml, inspire_schemas/utils.py, tests/unit/test_reference_builder.py
ref: cern-sis/issues-inspire#218
=> arxiv: enable doi format in references

inspire_schemas/records/conferences.yml, tests/unit/test_conference_builder.py
ref: https://github.com/cern-sis/issues-inspire/issues/404
=> conferences: make titles mandatory

.pre-commit-config.yaml, inspire_schemas/builders/__init__.py, inspire_schemas/builders/data.py, tests/integration/test_builders.py, tests/unit/test_data_builder.py
ref: https://github.com/cern-sis/issues-inspire/issues/621
=> Add data builder

docs/conf.py, inspire_schemas/records/data.yml, setup.cfg, tests/unit/test_data_builder.py
* ref: cern-sis/issues-inspire/issues/778
=> schema[data]: set mandatory fields as required

inspire_schemas/builders/signatures.py, tests/unit/test_signature_builder.py
ref: https://github.com/cern-sis/issues-inspire/issues/777
=> extract RORs from raw affiliations

inspire_schemas/records/data.yml, inspire_schemas/records/hep.yml
Add a type for data items, which should help fixing this: https://github.com/cern-sis/issues-inspire/issues/769
=> add data item type

inspire_schemas/builders/literature.py, inspire_schemas/builders/references.py, inspire_schemas/utils.py, setup.py
* ref https://github.com/cern-sis/issues-inspire/issues/902
=> isbn: use new isbnlib

Dockerfile, Dockerfile.py2, inspire_schemas/records/authors.yml, inspire_schemas/records/conferences.yml, inspire_schemas/records/data.yml, inspire_schemas/records/experiments.yml, inspire_schemas/records/hep.yml, inspire_schemas/records/institutions.yml, inspire_schemas/records/jobs.yml, inspire_schemas/records/journals.yml, inspire_schemas/records/seminars.yml, inspire_schemas/utils.py, setup.cfg, setup.py, tests/unit/test_api.py
* ref https://github.com/cern-sis/issues-inspire/issues/938
=> jsonschema: use fast validator for py3
